### ISSUE TITLE
website cannot be found

### ISSUE THREAD

**Issue by ousia** [textile/textile-spec#1]
@jgarber, I’m afraid that http://textileit.com cannot be found by my browser.

Do you intend to activate the site or am I missing something?

**Comment by sebix** [comment]
The Website should be http://txstyle.org/ @netcarver @jgarber

**Comment by netcarver** [comment]
I've removed the out-dated link from the repo and have left it blank as I there is not, yet, a single reference implementation we can link to as the "website" of the repository. 

I think I'd prefer to keep this repo totally free of links and let the language-specific repos connect out to their own reference sites.

**Comment by sebix** [comment]
It would be great to have
- a reference implementation linked, so we can check against it.
- a website which links all relevant webpages, repositories etc.

**Comment by ousia** [comment]
I guess the issue has been solved.
